name: CI/CD Pipeline

on:
  push:
    branches: [pull]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Run SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: sqp_6543e389980a8a3a0a5f16dca49265242e2a95bc
          SONAR_HOST_URL: http://localhost:9000
        with:
          args: >
            -Dsonar.projectKey=Email-Browser
            -Dsonar.sources=.
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.login=sqp_6543e389980a8a3a0a5f16dca49265242e2a95bc

      - name: Install dependencies
        run: npm install --force

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: kevinswiftxco/demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker
        run: docker build -t kevinswiftxco/demo-app .

      - name: Publish Image to Docker Hub
        run: docker push kevinswiftxco/demo-app:latest
