name: CI/CD Pipeline

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

     strategy:
      matrix:
        node-version: [20.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build 

