name: CI/CD Pipeline

on:
  push:
    branches: [pull]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Run SonarQube Scan
        run: npm run sonar

      - name: Install dependencies
        run: npm install --force

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: kevinswiftxco/demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker
        run: docker build -t kevinswiftxco/demo-app .

      - name: Publish Image to Docker Hub
        run: docker push kevinswiftxco/demo-app:latest
